import {
  calculateCCI,
  calculateCOPPOCK,
  calculateEMA,
  calculateImpulse,
  calculateKDJ,
  calculateMACD,
  calculateMFIPremium,
  calculateMFI,
  calculateRandom,
  calculateRSI,
  calculateRVGI,
  calculateSMA,
  calculateStochastic,
  calculateZLMA,
  calculateCTI,
  calculateATR,
  calculateRV,
  calculateRegime,
  calculateVWAP,
  calculateCVD,
} from "../indicators-functions"
import { IndicatorTypeMap } from "../indicators.interface"

export const indicatorsCalculatorsMap = {
  [IndicatorTypeMap.SMA]: calculateSMA,
  [IndicatorTypeMap.EMA]: calculateEMA,
  [IndicatorTypeMap.RSI]: calculateRSI,
  [IndicatorTypeMap.MACD]: calculateMACD,
  [IndicatorTypeMap.Stochastic]: calculateStochastic,
  [IndicatorTypeMap.Coppock]: calculateCOPPOCK,
  [IndicatorTypeMap.Random]: calculateRandom,
  [IndicatorTypeMap.Impulse]: calculateImpulse,
  [IndicatorTypeMap.RVGI]: calculateRVGI,
  [IndicatorTypeMap.ZLMA]: calculateZLMA,
  [IndicatorTypeMap.MFI]: calculateMFI,
  [IndicatorTypeMap.MFIPremium]: calculateMFIPremium,
  [IndicatorTypeMap.CCI]: calculateCCI,
  [IndicatorTypeMap.KDJ]: calculateKDJ,
  [IndicatorTypeMap.CTI]: calculateCTI,
  [IndicatorTypeMap.ATR]: calculateATR,
  [IndicatorTypeMap.RV]: calculateRV,
  [IndicatorTypeMap.Regime]: calculateRegime,
  [IndicatorTypeMap.VWAP]: calculateVWAP,
  [IndicatorTypeMap.CVD]: calculateCVD,
} as const
